In [ ]:
import numpy as np
import pandas as pd

In [ ]:
#Uploading all files with mounted google drive
train = pd.read_csv('/content/drive/MyDrive/Fall 2020/Intro to Machine Learning Applications/Project/act_train.csv')
test = pd.read_csv('/content/drive/MyDrive/Fall 2020/Intro to Machine Learning Applications/Project/act_test.csv')
people = pd.read_csv('/content/drive/MyDrive/Fall 2020/Intro to Machine Learning Applications/Project/people.csv')

In [ ]:
#Count of null values in train
print(train.isnull().sum())

people_id                  0
activity_id                0
date                       0
activity_category          0
char_1               2039676
char_2               2039676
char_3               2039676
char_4               2039676
char_5               2039676
char_6               2039676
char_7               2039676
char_8               2039676
char_9               2039676
char_10               157615
outcome                    0
dtype: int64


In [ ]:
#Count of null values in people
print(people.isnull().sum())

people_id    0
char_1       0
group_1      0
char_2       0
date         0
char_3       0
char_4       0
char_5       0
char_6       0
char_7       0
char_8       0
char_9       0
char_10      0
char_11      0
char_12      0
char_13      0
char_14      0
char_15      0
char_16      0
char_17      0
char_18      0
char_19      0
char_20      0
char_21      0
char_22      0
char_23      0
char_24      0
char_25      0
char_26      0
char_27      0
char_28      0
char_29      0
char_30      0
char_31      0
char_32      0
char_33      0
char_34      0
char_35      0
char_36      0
char_37      0
char_38      0
dtype: int64


In [ ]:
#Merging the train and test datasets with the people datatset
train = pd.merge(train, people, on='people_id')
test = pd.merge(test, people, on='people_id')

In [ ]:
#Training Data Pre-Processing  

y_train = train['outcome']

data = train.drop(['outcome','date_x','date_y'],axis=1).copy()



# clean
data[['activity_category','activity_id','char_1_x','char_2_x','char_3_x','char_4_x','char_5_x','char_6_x','char_7_x','char_8_x','char_9_x','char_10_x']]  = data[['activity_category','activity_id','char_1_x','char_2_x','char_3_x','char_4_x','char_5_x','char_6_x','char_7_x','char_8_x','char_9_x','char_10_x']].fillna('type 0')
data[['char_1_y','char_2_y','char_3_y','char_4_y','char_5_y','char_6_y','char_7_y','char_8_y','char_9_y']]  = data[['char_1_y','char_2_y','char_3_y','char_4_y','char_5_y','char_6_y','char_7_y','char_8_y','char_9_y']].fillna('type 0')

# Make each char numeric
data['people_id'] = pd.to_numeric( data['people_id'].apply(lambda x: x.split('_')[1]) )
data['activity_id'] = pd.to_numeric( data['activity_id'].apply(lambda x: x.split('_')[1]) )
data['activity_category'] = pd.to_numeric( data['activity_category'].apply(lambda x: str(x).split(' ')[1]) )

# numeric for x 1-10
for i in range(1,11):
  data['char_'+str(i)+'_x'] = pd.to_numeric( data['char_'+str(i)+'_x'].apply(lambda x: str(x).split(' ')[1]) )

# numeric for y 1-9
for i in range(1,10):
  data['char_'+str(i)+'_y'] = pd.to_numeric( data['char_'+str(i)+'_y'].apply(lambda x: str(x).split(' ')[1]) )


# convert bools to integer 11-37 
for i in range(10, 38):
  if(i==10):
    data['char_'+str(i)+"_y"] = data['char_'+str(i)+"_y"].astype(int)
  else:
    data['char_'+str(i)] = data['char_'+str(i)].astype(int)

data['group_1'] = pd.to_numeric( data['group_1'].apply(lambda x: str(x).split(' ')[1]) )

#print(data.dtypes)
#print(data)

In [ ]:
# Test Data Pre-Processing
data2 = test.drop(['date_x','date_y'],axis=1).copy()


# clean
data2[['activity_category','activity_id','char_1_x','char_2_x','char_3_x','char_4_x','char_5_x','char_6_x','char_7_x','char_8_x','char_9_x','char_10_x']]  =data2[['activity_category','activity_id','char_1_x','char_2_x','char_3_x','char_4_x','char_5_x','char_6_x','char_7_x','char_8_x','char_9_x','char_10_x']].fillna('type 0')
data2[['char_1_y','char_2_y','char_3_y','char_4_y','char_5_y','char_6_y','char_7_y','char_8_y','char_9_y']]  =data2[['char_1_y','char_2_y','char_3_y','char_4_y','char_5_y','char_6_y','char_7_y','char_8_y','char_9_y']].fillna('type 0')

# Make each char numeric
data2['people_id'] = pd.to_numeric( data2['people_id'].apply(lambda x: x.split('_')[1]) )
data2['activity_id'] = pd.to_numeric( data2['activity_id'].apply(lambda x: x.split('_')[1]) )
data2['activity_category'] = pd.to_numeric( data2['activity_category'].apply(lambda x: str(x).split(' ')[1]) )

# numeric for x 1-10
for i in range(1,11):
  data2['char_'+str(i)+'_x'] = pd.to_numeric( data2['char_'+str(i)+'_x'].apply(lambda x: str(x).split(' ')[1]) )

# numeric for y 1-9
for i in range(1,10):
  data2['char_'+str(i)+'_y'] = pd.to_numeric( data2['char_'+str(i)+'_y'].apply(lambda x: str(x).split(' ')[1]) )


# convert bools to integer 11-37 
for i in range(10, 38):
  if(i==10):
    data2['char_'+str(i)+"_y"] = data2['char_'+str(i)+"_y"].astype(int)
  else:
    data2['char_'+str(i)] = data2['char_'+str(i)].astype(int)

data2['group_1'] = pd.to_numeric( data2['group_1'].apply(lambda x: str(x).split(' ')[1]) )

#print(data2.dtypes)
#print(data2)


In [ ]:
# PCA

import plotly.express as px
#create list of feature names
initial_feature_names = []
for col in data.columns:
  initial_feature_names.append(col)
print(initial_feature_names)

#run pca
from sklearn.decomposition import PCA
pca = PCA(n_components=51)
pca.fit(data, y_train)

#get number of components and most important components
n_pcs = pca.components_.shape[0]
most_important = [np.abs(pca.components_[i]).argmax() for i in range(n_pcs)]

#list of names in order of variance explained
most_important_names = [initial_feature_names[most_important[i]] for i in range(n_pcs)]
print(most_important_names)

#list of variances
variances = pca.explained_variance_ratio_
print(variances)

#graph
exp_var_cumul = np.cumsum(pca.explained_variance_ratio_)

px.area(
    x = range(1, exp_var_cumul.shape[0] + 1),
    y = exp_var_cumul,
    labels={"x": "# Components", "y": "Explained Variance"}
)

# people_id and activity_category account for 99% of variance each


['people_id', 'activity_category', 'char_1_x', 'char_2_x', 'char_3_x', 'char_4_x', 'char_5_x', 'char_6_x', 'char_7_x', 'char_8_x', 'char_9_x', 'char_10_x', 'char_1_y', 'group_1', 'char_2_y', 'char_3_y', 'char_4_y', 'char_5_y', 'char_6_y', 'char_7_y', 'char_8_y', 'char_9_y', 'char_10_y', 'char_11', 'char_12', 'char_13', 'char_14', 'char_15', 'char_16', 'char_17', 'char_18', 'char_19', 'char_20', 'char_21', 'char_22', 'char_23', 'char_24', 'char_25', 'char_26', 'char_27', 'char_28', 'char_29', 'char_30', 'char_31', 'char_32', 'char_33', 'char_34', 'char_35', 'char_36', 'char_37', 'char_38']
['people_id', 'group_1', 'char_10_x', 'char_38', 'char_3_y', 'char_7_y', 'char_1_x', 'char_4_y', 'char_9_y', 'char_1_x', 'char_9_y', 'char_5_y', 'char_2_x', 'char_8_y', 'activity_category', 'char_6_y', 'char_8_x', 'char_2_y', 'char_5_x', 'char_31', 'char_8_x', 'char_7_x', 'char_25', 'char_18', 'char_16', 'char_25', 'char_15', 'char_4_x', 'char_4_x', 'char_10_y', 'char_28', 'char_14', 'char_35', 'char_

In [ ]:
# Random Forest Classifier Model
from sklearn.ensemble import RandomForestClassifier 

clf = RandomForestClassifier(max_depth=3, random_state=99)
clf.fit(data, y_train)
print(clf.predict(data2))

[1 1 1 ... 0 0 0]


In [ ]:
# Printing results to csv for submission
final_submission = pd.DataFrame({ 'activity_id' : test['activity_id'].values, 
                       'outcome': clf.predict_proba(data2)[:,1] })
final_submission.to_csv('Red_Hat_rfc.csv', index=False) 

In [ ]:
# LGBMC Classifier Model
from lightgbm import LGBMClassifier

lgbm = LGBMClassifier(max_depth= 3, random_state=99)
lgbm.fit(data, y_train)
print(lgbm.predict(data2))

[1 1 1 ... 0 0 0]


In [ ]:
# Printing results to csv for submission
final_submission = pd.DataFrame({ 'activity_id' : test['activity_id'].values, 
                       'outcome': lgbm.predict_proba(data2)[:,1] })
final_submission.to_csv('Red_Hat_lgbmc.csv', index=False) 

In [ ]:
# Decision Trees Classifier 
from sklearn.tree import DecisionTreeClassifier 

tree = DecisionTreeClassifier(random_state=99)
tree.fit(data, y_train)
print(tree.predict(data2))

[0 0 1 ... 0 0 0]


In [ ]:
# Printing results to csv for submission
final_submission = pd.DataFrame({ 'activity_id' : test['activity_id'].values, 
                       'outcome': tree.predict_proba(data2)[:,1] })
final_submission.to_csv('Red_Hat_dtc.csv', index=False) 